### PR TITLE
Support for GaussianMixtures.jl

### PR DESCRIPTION
**Pull request by cstjean**
@davidavdav I've added support for GaussianMixtures to ScikitLearn.jl. Could you please review the GaussianMixtures.jl file in this PR to make sure that nothing is out-of-place? You might also be interested in [this sample notebook](https://github.com/cstjean/ScikitLearn.jl/blob/f2ea86aecbae600940d56349b0c681874a3569f8/examples/Density_Estimation_Julia.ipynb)

I've made the PR against ScikitLearn.jl (using `@require`), but I would prefer if the code lived in GaussianMixtures.jl. We would import from [ScikitLearnBase.jl](https://github.com/cstjean/ScikitLearnBase.jl), which is a skeleton package. If that sounds fine for you, I'll move this PR over there.

### CODE REVIEW

**Comment by davidavdav** [comment]
Hello, 

I now see why you submitted a PR for un-initialized GMMs to GaussianMixtures.jl.  Is the idea that Scikit.Learn defines an interface, and that this PR provides such an interface to GaussianMixtures?

Regarding the notebook: for full-covariance GMMs I would recommend the variational Bayes training, this should find the number of Gaussians more/less automatically (starting from too many Gaussians).  

The code looks OK, just the density function appears somewhat difficult.  But it is true that some of these basic functions do not have an interface, as GaussianMixtures was written for specific training and a particular use.

**Comment by cstjean** [comment]
> Is the idea that Scikit.Learn defines an interface, and that this PR provides such an interface to GaussianMixtures?

Yeah, JuMP/MathProgBase employ a similar strategy. ScikitLearnBase.jl defines the interface to ScikitLearn.jl. That way, it's a tiny dependency for packages who want to implement it.

> Regarding the notebook: for full-covariance GMMs I would recommend the variational Bayes training, this should find the number of Gaussians more/less automatically (starting from too many Gaussians).

That's a good point. My goal was more to test that get/set_params! were implemented correctly, but I'll leave a note about it in the notebook.

It would be cool to implement the scikit-learn interface for VGMM, but AFAICT we'd have to change the type definition slightly for that...

> The code looks OK, just the density function appears somewhat difficult. 

You're right, will fix.

> But it is true that some of these basic functions do not have an interface, as GaussianMixtures was written for specific training and a particular use. 

It works very well so far, it's a good native replacement for the Python version.

**Comment by davidavdav** [comment]
Thanks, I think I understand now.  

One question---in ScikitLearn, does data "run down" or "run sideways", i.e., are data point stacked vertically or horizontally?

I've thought long about it, and decided that data should run down for GaussianMixtures, like in DataFrames.  But still, I am not convinced this is a right choice---mainly because of the (imho bad) choice of Julia to be column-major.  The interaction of these choices makes streaming of data hard (not that I do that now, but it just the idea).

**Comment by cstjean** [comment]
Data runs down. I agree with you that it's not ideal given Julia's column-major status, but once Julia has transposed views, `X'` should be a negligible operation.

**Pull request closed without merging**
